Repository GRPC-OK/Intellisia, pull requests merged in 2025-05, with the labels that each got.

#8 chore: 웹 서버 초기 환경 구축
  .gitignore
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  public/favicon.ico
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tsconfig.json
Labels: chore

#9 chore: Pull requests 검증을 위해 eslint.yml 추가합니다.
  .github/workflows/eslint.yml
  eslint.config.mjs
  package-lock.json
  package.json
Labels: chore

#12 chore: 이슈 템플릿, PR 템플릿, ESLint/Prettier 설정 추가
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc.json
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
Labels: chore

#22 refactor: 프로젝트 상세페이지 컴포넌트 및 UI 구조 개선
  package-lock.json
  package.json
  src/components/project-detail/ContributorsAvatars.tsx
  src/components/project-detail/ProjectHeader.tsx
  src/components/project-detail/ProjectSidebar.tsx
  src/components/project-detail/VersionCard.tsx
  src/components/project-detail/VersionList.tsx
  src/pages/project/[projectId].tsx
  src/types/project.ts
Labels: refactor

#24 feat: 프로젝트 상세 페이지 조회 API 구현
  package-lock.json
  package.json
  prisma/migrations/20250515174015_init/migration.sql
  prisma/migrations/20250515181202_make_avatar_required/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/components/project-detail/ContributorsAvatars.tsx
  src/components/project-detail/ProjectSidebar.tsx
  src/components/project-detail/SortControl.tsx
  src/dtos/project/toProjectDetailDto.ts
  src/lib/prisma.ts
  src/pages/api/hello.ts
  src/pages/api/projects/[projectId].ts
  src/pages/project/[projectId].tsx
  src/repositories/project/getProjectById.ts
  src/repositories/version/getVersionsByProject.ts
  src/services/project/getProjectDetail.ts
  src/types/project.ts
Labels: feat

#26 feat: 버전 플로우 상태 조회 API 구현
  package-lock.json
  package.json
  prisma/migrations/20250515181202_make_avatar_required/migration.sql
  prisma/migrations/20250517071020_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/dtos/project/toProjectDetailDto.ts
  src/dtos/versions/VersionFlowStatusResponseDto.ts
  src/pages/api/projects/[projectId].ts
  src/pages/api/versions/[versionId]/flow-status.ts
  src/pages/project/[projectId].tsx
  src/pages/test.tsx
  src/repositories/project.repository.ts
  src/repositories/version.repository.ts
  src/repositories/version/getVersionsByProject.ts
  src/services/project.service.ts
  src/services/version.service.ts
  src/types/project.ts
  tsconfig.seed.json
Labels: feat

#33 feat: Semgrep 정적 분석 워크플로우 추가
  .github/workflows/semgrep.yml
Labels: feat

#29 docker-analysis-page 수정
  src/pages/code-analysis.tsx
  src/pages/deployment-approval.tsx
  src/pages/docker-analysis.tsx
  src/pages/image-analysis.tsx
Labels: refactor

#44 refactor: semgrep 결과 sarif 파일에서 불필요한 메타데이터 제거
  .github/workflows/semgrep.yml
Labels: refactor

#31 feat: 코드 정적 분석 자동화 백엔드 구현
  .github/workflows/semgrep.yml
  package-lock.json
  package.json
  prisma/migrations/20250518175057_init_code_analysis/migration.sql
  prisma/migrations/20250518180205_init/migration.sql
  prisma/migrations/20250519060627_add_code_analysis_fields/migration.sql
  prisma/migrations/20250519062716_add_severity_cwe_cve/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/application/code-analysis/start-code-analysis.ts
  src/pages/api/projects/[projectId].ts
  src/pages/api/versions/[versionId]/code-analysis.ts
  src/pages/api/versions/[versionId]/confirm.ts
  src/pages/api/versions/[versionId]/flow-status.ts
  src/pages/code-analysis.tsx
  src/services/code-analysis-service/code-analysis.service.ts
  src/services/code-analysis-service/trigger-semgrep-workflow.ts
  src/services/version-service/version-status-updater.service.ts
  src/types/sarif.ts
  src/utils/parseSarifSemgrep.ts
Labels: feat

#47 feat: 코드 정적 분석 페이지 프론트엔드 구현
  src/components/code-analysis/CodeAnalysisErrorLog.tsx
  src/components/code-analysis/CodeAnalysisStatusView.tsx
  src/components/code-analysis/CodeIssueCard.tsx
  src/components/code-analysis/CodeIssueList.tsx
  src/pages/project/[projectId]/index.tsx
  src/pages/project/[projectId]/version/[versionId]/code-analysis/[issueId].tsx
  src/pages/project/[projectId]/version/[versionId]/code-analysis/index.tsx
  src/types/code-analysis.ts
Labels: feat

#49 fix: tx 암묵적 any 타입 오류 수정
  src/services/code-analysis-service/code-analysis.service.ts
Labels: fix

#54 feat: rds 추가
  .github/workflows/build.yml
  dockerfile
  entrypoint.sh
Labels: feat

#55 fix: Dockerfile에 Prisma generate 추가 및 CI 빌드 오류 수정
  dockerfile
  entrypoint.sh
Labels: fix

#60 fix: eslint-error-fix
  package-lock.json
  src/pages/deployment-approval.tsx
  src/pages/index.tsx
Labels: fix

#59 feat:프로젝트 ui 구성
  src/pages/create-project.tsx
Labels: feat

#64 fix: CI/CD build error fix
  .github/workflows/build.yml
  dockerfile
Labels: fix

#65 refactor: schema더미파일 test
  prisma/schema.prisma
Labels: refactor

#66 feat:사용자 데이터 액세스를 위한 UserDBS 서비스 구현
  .gitignore
  src/services/db-access-service/user.db.service.ts
Labels: feat

#71 feat:Project 데이터 접근 서비스 구현
  src/services/db-access-service/project.db.service.ts
Labels: feat

#83 chore: migration 파일 자동 생성 스크립트 추가
  package.json
  prisma/migrations/20250521145706_date/migration.sql
Labels: chore

#78 fix:UserDBService에 전체 사용자 조회 기능 추가 및 리팩토링
  src/services/db-access-service/project.db.service.ts
  src/services/db-access-service/user.db.service.ts
Labels: fix

#84 feat,fix:신규 Project 생성 API (POST /api/projects) 구현 및 관련 타입 정의 수정
  prisma/schema.prisma
  src/dtos/project/toProjectDetailDto.ts
  src/pages/api/projects/index.ts
  src/services/project.service.ts
Labels: feat, fix

#96 fix:오류수정
  prisma/migrations/20250522092911_/migration.sql
  src/dtos/project/toProjectDetailDto.ts
Labels: fix

#89 chore: ec2에 env 파일 주입되도록 추가
  .github/workflows/build.yml
Labels: chore

#98 feat: 버전 상세 페이지 상단 헤더 정보 반환 api 구현
  src/dtos/versions/toVersionHeaderDto.ts
  src/pages/api/versions/[versionId]/index.ts
  src/repositories/version.repository.ts
  src/types/version.ts
Labels: feat

#102 feat:배포 준비 페이지 프론트엔드 목업 구현
  src/pages/project/[projectId]/prepare-run.tsx
Labels: feat

#103 feat,fix:파이프라인 실행 설정 페이지 UI 및 기본 API 구현
  prisma/migrations/20250523063920_add_unique_to_project_name/migration.sql
  prisma/schema.prisma
  src/pages/api/projects/[projectName].ts
  src/pages/api/projects/[projectName]/versions/initiate-pipeline.ts
  src/pages/project/[projectName]/index.tsx
  src/pages/project/[projectName]/prepare-run.tsx
  src/pages/project/[projectName]/version/[versionId]/code-analysis/[issueId].tsx
  src/pages/project/[projectName]/version/[versionId]/code-analysis/index.tsx
  src/pages/workflow.tsx
Labels: feat, fix

#104 fix: 배포 준비 페이지 백엔드 api 오류 수정
  src/pages/api/project/[projectName].ts
  src/pages/api/project/[projectName]/versions/initiate-pipeline.ts
  src/pages/api/project/create.ts
  src/pages/api/project/dashboard_projects.ts
  src/pages/create-project.tsx
  src/pages/dashboard.tsx
  src/pages/project/[projectName]/index.tsx
  src/pages/project/[projectName]/prepare-run.tsx
  src/pages/project/[projectName]/version/[versionId]/code-analysis/index.tsx
  src/pages/project/[projectName]/workflow.tsx
Labels: fix

#105 feat: 이미지 빌드 UI 및 백엔드 API 구현
  .github/workflows/image_build.yml
  prisma/schema.prisma
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/image-build/image-build.ts
  src/pages/api/image-build/result.ts
  src/pages/api/image-build/start.ts
  src/pages/image-build.tsx
  src/styles/image-build.module.css
Labels: feat, refactor

#110 refactor: 프로젝트 상세 및 버전 조회 API 구조 개선 및 서비스 레이어 분리
  prisma/migrations/20250524090353_date/migration.sql
  prisma/schema.prisma
  src/dtos/project/toProjectDetailDto.ts
  src/dtos/versions/toVersionSummaryList.ts
  src/pages/api/project/[projectName].ts
  src/pages/api/project/[projectName]/index.ts
  src/pages/api/projects/[projectName].ts
  src/pages/api/versions/index.ts
  src/pages/project/[projectName]/index.tsx
  src/repositories/project.repository.ts
  src/services/project.service.ts
  src/services/version.service.ts
  src/types/project.ts
Labels: feat, refactor

#112 fix: VersionCard 타입 요구에 맞춰 id prop 전달
  src/components/project-detail/VersionList.tsx
Labels: fix

#114 ecr 레포 지정
  .github/workflows/image_build.yml
Labels: fix

#113 feat: 프로젝트 상세 페이지에 배포 버튼 추가 및 버전 생성 페이지로 이동 기능 구현
  src/components/project-detail/NewDeploymentButton.tsx
  src/components/project-detail/ProjectSidebar.tsx
  src/pages/project/[projectName]/index.tsx
Labels: feat

#116 fix: callback_url, project id 삭제
  .github/workflows/image_build.yml
Labels: fix

#118 feat: VersionFlowPage 상태 흐름 및 승인 처리 로직 구현
  .github/workflows/semgrep.yml
  package-lock.json
  package.json
  prisma/migrations/20250524160836_date/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/application/code-analysis/start-code-analysis.ts
  src/components/code-analysis/CodeAnalysisEmptyView.tsx
  src/components/code-analysis/CodeAnalysisErrorLog.tsx
  src/components/code-analysis/CodeAnalysisErrorView.tsx
  src/components/code-analysis/CodeAnalysisStatusView.tsx
  src/components/code-analysis/CodeAnalysisViewer.tsx
  src/components/code-analysis/CodeIssueCard.tsx
  src/components/code-analysis/CodeIssueList.tsx
  src/components/version/ApprovalModal.tsx
  src/components/version/FlowConnector.tsx
  src/components/version/FlowStage.tsx
  src/components/version/ReviewDeployButton.tsx
  src/components/version/VersionHeader.tsx
  src/dtos/versions/VersionFlowStatusResponseDto.ts
  src/lib/version-flow-utils.ts
  src/pages/api/project/[projectName]/versions/initiate-pipeline.ts
  src/pages/api/versions/[versionId]/code-analysis.ts
  src/pages/api/versions/[versionId]/index.ts
  src/pages/api/versions/[versionId]/start-flow.ts
  src/pages/project/[projectName]/version/[versionId]/code-analysis/[issueId].tsx
  src/pages/project/[projectName]/version/[versionId]/code-analysis/index.tsx
  src/pages/project/[projectName]/version/[versionId]/index.tsx
  src/services/code-analysis-service/code-analysis.service.ts
  src/services/code-analysis-service/handle-semgrep-result.service.ts
  src/services/version.service.ts
  src/types/sarif.ts
  src/types/version-flow.ts
  src/utils/parseSarifSemgrep.ts
  tsconfig.json
Labels: feat

#125 docs:README.md 파일 작성 및 docs 문서화에 관한 변경 사항
  README.md
Labels: docs

#129 chore: ECR 대신 도커 허브에 이미지를 올리도록 image_build.yml 파일을 변경
  .github/workflows/image_build.yml
Labels: chore

#130 fix:프로젝트 생성 로직 개선 및 오류 수정
  src/pages/create-project.tsx
Labels: fix

#136 feat: 자동 버전 네이밍을 위한 최신 버전 조회 및 중복 시 대응 로직 추가
  src/services/version-service/version-generator.service.ts
Labels: feat

#139 feat: 파이프라인 시작 버튼 클릭 시 분석 및 빌드 트리거 되도록 연결
  .github/workflows/semgrep.yml
  prisma/seed.ts
  src/application/code-analysis/start-code-analysis.ts
  src/application/code-analysis/start-full-flow.ts
  src/pages/api/project/[projectName]/start-flow.ts
  src/pages/api/project/[projectName]/versions/initiate-pipeline.ts
  src/pages/api/versions/[versionId]/start-flow.ts
  src/pages/project/[projectName]/prepare-run.tsx
  src/services/version-service/initiate-version.service.ts
  src/services/version-service/processor/version-generator.ts
  src/services/version-service/version-generator.service.ts
  src/services/version-service/version-status-updater-with-tx.service.ts
Labels: feat, fix, refactor

#140 refactor: 프론트 페이지 필드값 리팩토링
  src/pages/create-project.tsx
  src/pages/project/[projectName]/prepare-run.tsx
Labels: refactor

#144 fix: 필요없는 api 제거 및 버전 생성 페이지 수정
  src/pages/api/project/[projectName]/versions/initiate-pipeline.ts
  src/pages/project/[projectName]/prepare-run.tsx
  tsconfig.json
Labels: fix

#145 chore: GitHub 토큰 환경변수 이름 변경
  .github/workflows/semgrep.yml
  src/application/start-full-flow.ts
Labels: chore

#146 feat: Semgrep SARIF 결과를 sarif-web-component로 시각화하는 기능 추가
  .npmrc
  package-lock.json
  package.json
  src/components/code-analysis/CodeAnalysisEmptyView.tsx
  src/components/code-analysis/CodeAnalysisErrorView.tsx
  src/components/code-analysis/CodeAnalysisViewer.tsx
  src/pages/api/project/[projectName]/start-flow.ts
  src/pages/api/versions/[versionId]/code-analysis/error-log.ts
  src/pages/api/versions/[versionId]/code-analysis/index.ts
  src/pages/api/versions/[versionId]/code-analysis/sarif.ts
  src/pages/api/versions/[versionId]/code-analysis/status.ts
  src/pages/project/[projectName]/version/[versionId]/code-analysis/index.tsx
Labels: feat

#155 refactor: flow-status polling 중단 조건 제거
  src/pages/project/[projectName]/version/[versionId]/index.tsx
Labels: refactor

#157 feat:배포 결과 콜백 api & 승인 결정 api 분석 구현
  src/pages/api/deployment/callback.ts
  src/pages/api/versions/[versionId]/approval-decision.ts
Labels: feat

#161 feat:배포 실행 버튼 & 플로우 페이지 구현
  src/components/version/DeployButton.tsx
  src/pages/project/[projectName]/version/[versionId]/index.tsx
  src/services/deployment-service/trigger-deployment-workflow.ts
Labels: feat

#164 feat: 이미지 정적 분석 결과 처리 및 SARIF 데이터 조회 로직을 구현
  next.config.ts
  src/pages/api/image-analysis/callback_analysis.ts
  src/pages/api/versions/[versionId]/image-analysis.ts
  src/pages/project/[projectName]/version/[versionId]/image-analysis/index.tsx
Labels: feat

#168 fix: 이미지 정적 분석 결과 처리 및 SARIF 데이터 조회 로직을 구현 -> Actions 오류 수정
  src/pages/api/versions/[versionId]/image-analysis.ts
Labels: fix

#171 refactor: 코드 정적 분석 API 통합 및 이미지 분석/빌드 흐름 수정
  .github/workflows/image_build_and_scan.yml
  src/application/trigger-deployment-after-approval.ts
  src/components/version/FlowStage.tsx
  src/lib/version-flow-utils.ts
  src/pages/api/versions/[versionId]/approval-decision.ts
  src/pages/api/versions/[versionId]/code-analysis/error-log.ts
  src/pages/api/versions/[versionId]/code-analysis/result.ts
  src/pages/api/versions/[versionId]/code-analysis/sarif.ts
  src/pages/api/versions/[versionId]/code-analysis/status.ts
  src/pages/api/versions/[versionId]/deploy.ts
  src/pages/api/versions/[versionId]/image-analysis.ts
  src/pages/api/versions/[versionId]/image-analysis/callback_analysis.ts
  src/pages/api/versions/[versionId]/image-analysis/index.ts
  src/pages/api/versions/[versionId]/image-build/callback_build.ts
  src/pages/api/versions/[versionId]/image-build/trigger-image-workflow.ts
  src/pages/project/[projectName]/version/[versionId]/code-analysis/index.tsx
  src/pages/project/[projectName]/version/[versionId]/index.tsx
Labels: feat, fix, refactor

#173 refactor: 이미지 빌드와 이미지 분석 백엔드 리펙토링 완료
  src/pages/api/versions/[versionId]/image-analysis/callback_analysis.ts
  src/pages/api/versions/[versionId]/image-analysis/index.ts
  src/pages/api/versions/[versionId]/image-build/callback_build.ts
  src/pages/deployment-approval.tsx
  src/pages/deployment.tsx
  src/pages/image-analysis.tsx
  src/pages/image-build.tsx
  src/pages/project/[projectName]/workflow.tsx
  src/pages/workflow.tsx
Labels: refactor

#175 feature : 배포 페이지 버튼 활성화
  src/pages/project/[projectName]/version/[versionId]/deployment-executed/index.tsx
Labels: feat

#180 feat: deploy 되도록 연결 및 refactoring
  .github/workflows/deploy.yml
  .github/workflows/image_build_and_scan.yml
  src/application/trigger-deployment-after-approval.ts
  src/components/version/RetryDeploymentButton.tsx
  src/components/version/RetryDeploymentModal.tsx
  src/pages/api/project/create.ts
  src/pages/api/versions/[versionId]/approval-decision.ts
  src/pages/api/versions/[versionId]/deployment/index.ts
  src/pages/api/versions/[versionId]/image-analysis.ts
  src/pages/api/versions/[versionId]/image-build/callback_build.ts
  src/pages/api/versions/[versionId]/manual-deploy.ts
  src/pages/api/versions/[versionId]/retry-deployment.ts
  src/pages/project/[projectName]/prepare-run.tsx
  src/pages/project/[projectName]/version/[versionId]/index.tsx
  src/services/deployment-service/trigger-deployment-workflow.ts
  src/services/version-service/initiate-version.service.ts
Labels: feat, fix, refactor
